export type PresetKey = "default" | "honda" | "petchana";
export type Language = "th" | "en" | "ja";

export type RoiInput = {
  peoplePerDay: number;
  daysPerMonth: number;
  minutesPerPerson: number;
  waitMinutes: number;
  tenkoMinutesPerPerson: number;
  workDaysYear: number;
  staffCount: number;
  salaryPerMonth: number;
  otHoursPerDay: number;
  otMultiplier: number;
  socialSecurityYear: number;
  bonusYear: number;
  absenceYear: number;
  employeeAvgSalary: number;
  workHoursDay: number;
  employeeCostFactor: number;
  alcBuy: number;
  alcMaint: number;
  alcCal: number;
  alcLife: number;
  bpBuy: number;
  bpMaint: number;
  bpCal: number;
  bpLife: number;
  tempBuy: number;
  tempMaint: number;
  tempCal: number;
  tempLife: number;
  tenkoMonthly: number;
  tenkoSetup: number;
  tenkoOtherYear: number;
  years: number;
};

export type RoiResult = {
  formulaVersion: string;
  people: number;
  daysM: number;
  daysY: number;
  min: number;
  wait: number;
  tenkoMin: number;
  staff: number;
  cycle: number;
  util: number;
  utilPct: number;
  status: "Excellent" | "Normal" | "Busy" | "Overloaded";
  statusColor: "green" | "yellow" | "orange" | "red";
  baseSalaryCost: number;
  otCost: number;
  staffExtras: number;
  oldLabor: number;
  oldDep: number;
  oldMaint: number;
  oldCal: number;
  oldTotal: number;
  newMonthly: number;
  newSetup: number;
  newOther: number;
  newTotal: number;
  newRecurring: number;
  oldTimeYear: number;
  newTimeYear: number;
  timeSaveYear: number;
  timeSaveDay: number;
  costPerMin: number;
  oldProd: number;
  newProd: number;
  prodSave: number;
  oldGrand: number;
  newGrand: number;
  annualSave: number;
  roi: number;
  isWorth: boolean;
  years: number;
  oldData: number[];
  newData: number[];
  otH: number;
};
