export const uiText = {
    th: {
        print: "พิมพ์ / Save PDF",
        fullWidth: "เต็มจอ",
        fullWidthOn: "กลับสู่ขนาดปกติ",
        fullWidthOff: "ขยาย layout ให้เต็มพื้นที่",
        eyebrow: "Single Page ROI Tool",
        titleA: "คำนวณ ROI แบบเดิม เทียบกับ",
        desc: "คำนวณต้นทุน เวลา Productivity Loss และความคุ้มค่าของ Tenko Robot พร้อม preset สำหรับแต่ละลูกค้า",
        inputTitle: "กรอกข้อมูล",
        inputSub: "แก้ตัวเลขได้ทันที ระบบจะคำนวณใหม่อัตโนมัติ",
        operation: "1) Operation",
        staffCost: "2) Staff Cost",
        productivity: "3) Inspection Time Cost",
        equipment: "4) Equipment Cost แบบเดิม",
        tenko: "5) Tenko Robot",
        workload: "WORKLOAD",
        cost: "COST",
        hiddenCost: "HIDDEN COST",
        equipmentTag: "EQUIPMENT",
        allIn: "ALL-IN",
        autoOtHint: "Default และ Petchana จะคำนวณ OT อัตโนมัติเมื่อ utilization เกิน 100% ส่วน Honda ใช้ค่า override 4 ชั่วโมง",
        autoOn: "Auto OT: ON - คำนวณจาก utilization เกิน 100%",
        autoOff: "Auto OT: OFF - ผู้ใช้หรือ preset กำหนดเอง",
        factorChoice: "Employee Cost Factor Choice",
        factorGeneral: "โรงงานทั่วไป",
        factorGeneralDesc: "ต้นทุนพื้นฐานนอกเหนือเงินเดือน",
        factorJapanese: "โรงงานญี่ปุ่น",
        factorJapaneseDesc: "สวัสดิการและมาตรฐาน HR สูงขึ้น",
        factorMultinational: "บริษัทข้ามชาติ",
        factorMultinationalDesc: "ต้นทุนพนักงานรวมสูงกว่าเงินเดือนมาก",
        factorCustom: "กำหนดเอง",
        factorHint: "Employee Cost Factor คือต้นทุนจริงของพนักงานนอกเหนือจากเงินเดือน เช่น ประกันสังคม โบนัส ยูนิฟอร์ม สวัสดิการ วันลา อบรม และค่า recruit/onboarding",
        reset: "Reset",
        saving: "ประหยัดเงิน / ปี",
        timeSaving: "ประหยัดเวลาตรวจ / ปี",
        prodSaving: "ประหยัด Productivity Loss / ปี",
        worth: "ความคุ้มค่า",
        worthGood: "คุ้มค่า",
        worthBad: "ไม่คุ้มค่า",
        worthGoodNote: "Tenko ประหยัดกว่าต่อปี",
        worthBadNote: "Tenko มีต้นทุนสูงกว่าแบบเดิม",
        oldMethod: "แบบเดิม",
        annualCost: "Annual Operating Cost",
        annualTime: "Annual Inspection Time",
        prodLoss: "Employee Productivity Loss",
        totalCost: "Total Cost Incl. Productivity",
        execTitle: "Executive Summary",
        execDesc: "สรุปต้นทุนและเวลาที่ประหยัดได้ต่อปี",
        costBreakTitle: "Cost Breakdown",
        costBreakDesc: "ต้นทุนแบบเดิมคิดค่าเจ้าหน้าที่ตาม utilization จริง ไม่ใช่เต็ม 100%",
        staffByUtil: "ค่าเจ้าหน้าที่ตาม Utilization",
        baseSalary: "เงินเดือนฐาน / ปี",
        otCost: "ค่า OT / ปี",
        extras: "ประกันสังคม + โบนัส + วันลา",
        dep: "ค่าเสื่อมอุปกรณ์ / ปี",
        maint: "บำรุงรักษา / ปี",
        cal: "สอบเทียบ / ปี",
        tenkoMonthly: "รายเดือน x 12",
        setup: "Setup ปีแรก",
        other: "อื่น ๆ / ปี",
        cycle: "Cycle Time แบบเดิม",
        costPerMin: "ต้นทุนพนักงาน / นาที",
        timeSaveDay: "เวลาตรวจที่ประหยัด / วัน",
        roiFromTotal: "ROI จาก Total Saving",
        chartTitle: "Cumulative Cost Chart",
        chartDesc: "Operating Cost + Productivity Loss ตามจำนวนปีที่เลือก",
        timeChartTitle: "Time Cost Chart",
        timeChartDesc: "เทียบเวลาตรวจต่อปีแบบมีและไม่มี Tenko พร้อมเวลาที่ประหยัดได้",
        timeChartAnnual: "ต่อปี",
        timeChartSaved: "ประหยัดเวลาตรวจ / ปี",
        start: "เริ่มต้น",
        year: "ปี",
        hours: "ชม.",
        min: "นาที",
        disclaimer: "รายงานนี้เป็นการประเมินจากข้อมูลและสมมติฐานที่ผู้ใช้กรอก ผลลัพธ์จริงอาจเปลี่ยนตามสภาพการใช้งานจริง",
        assumptions: "Key Assumptions",
        formula: "Formula",
        utilTitle: "Inspection Staff Utilization",
        utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
        productivityPanelDesc: "Cycle time, utilization, employee cost, and returned working time.",
        printHeroTitle: "EXECUTIVE SUMMARY",
        printHeroSubtitle: "Annual ROI comparison: Conventional method vs Tenko Robot",
        printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
        printDetailTitle: "CALCULATION DETAILS",
        printDetailSubtitle: "Calculation assumptions and cost breakdown",
        printConclusionTitle: "Conclusion",
        printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
        printBenefitSafeTitle: "Safer Workplace",
        printBenefitSafeDesc: "Reduce risk before work starts",
        printBenefitProdTitle: "Higher Productivity",
        printBenefitProdDesc: "Return inspection time to operations",
        printBenefitInvestTitle: "Smart Investment",
        printBenefitInvestDesc: "Clear annual saving and payback"
    },
    en: {
        print: "Print / Save PDF",
        fullWidth: "Full width",
        fullWidthOn: "Return to normal width",
        fullWidthOff: "Expand the layout to fill the screen",
        eyebrow: "Single Page ROI Tool",
        titleA: "Calculate conventional ROI versus",
        desc: "Estimate operating cost, inspection time, productivity loss, and Tenko Robot investment impact with customer presets.",
        inputTitle: "Inputs",
        inputSub: "Edit values and the calculator updates immediately.",
        operation: "1) Operation",
        staffCost: "2) Staff Cost",
        productivity: "3) Inspection Time Cost",
        equipment: "4) Conventional Equipment Cost",
        tenko: "5) Tenko Robot",
        workload: "WORKLOAD",
        cost: "COST",
        hiddenCost: "HIDDEN COST",
        equipmentTag: "EQUIPMENT",
        allIn: "ALL-IN",
        autoOtHint: "Default and Petchana calculate OT automatically when utilization exceeds 100%. Honda uses 4 hours as an override.",
        autoOn: "Auto OT: ON - calculated from utilization over 100%",
        autoOff: "Auto OT: OFF - user or preset override",
        factorChoice: "Employee Cost Factor Choice",
        factorGeneral: "General factory",
        factorGeneralDesc: "Basic cost beyond salary",
        factorJapanese: "Japanese factory",
        factorJapaneseDesc: "Higher welfare and HR standards",
        factorMultinational: "Multinational",
        factorMultinationalDesc: "Total employee cost is much higher than salary",
        factorCustom: "Custom",
        factorHint: "Employee Cost Factor represents real employee cost beyond salary, including social security, bonus, uniform, welfare, leave, training, and recruiting/onboarding.",
        reset: "Reset",
        saving: "Annual cost saving",
        timeSaving: "Annual inspection time saving",
        prodSaving: "Annual productivity loss saving",
        worth: "Investment result",
        worthGood: "Worth it",
        worthBad: "Not worth it",
        worthGoodNote: "Tenko saves annual cost",
        worthBadNote: "Tenko costs more than the conventional method",
        oldMethod: "Conventional",
        annualCost: "Annual Operating Cost",
        annualTime: "Annual Inspection Time",
        prodLoss: "Employee Productivity Loss",
        totalCost: "Total Cost Incl. Productivity",
        execTitle: "Executive Summary",
        execDesc: "Annual cost and time saving summary",
        costBreakTitle: "Cost Breakdown",
        costBreakDesc: "Conventional staff cost is calculated by real inspection utilization, not fixed at 100%.",
        staffByUtil: "Staff cost by utilization",
        baseSalary: "Base salary / year",
        otCost: "OT cost / year",
        extras: "Social security + bonus + leave",
        dep: "Equipment depreciation / year",
        maint: "Maintenance / year",
        cal: "Calibration / year",
        tenkoMonthly: "Monthly fee x 12",
        setup: "First-year setup",
        other: "Other cost / year",
        cycle: "Conventional cycle time",
        costPerMin: "Employee cost / minute",
        timeSaveDay: "Inspection time saved / day",
        roiFromTotal: "ROI from total saving",
        chartTitle: "Cumulative Cost Chart",
        chartDesc: "Operating cost + productivity loss by selected year range",
        timeChartTitle: "Time Cost Chart",
        timeChartDesc: "Compare annual inspection time with and without Tenko, plus annual time saved.",
        timeChartAnnual: "Annual",
        timeChartSaved: "Inspection time saved / year",
        start: "Start",
        year: "Year",
        hours: "hr",
        min: "min",
        disclaimer: "This report is an estimate based on user-entered assumptions. Actual results may vary by real operating conditions.",
        assumptions: "Key Assumptions",
        formula: "Formula",
        utilTitle: "Inspection Staff Utilization",
        utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
        productivityPanelDesc: "Cycle time, utilization, employee cost, and returned working time.",
        printHeroTitle: "EXECUTIVE SUMMARY",
        printHeroSubtitle: "Annual ROI comparison: Conventional method vs Tenko Robot",
        printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
        printDetailTitle: "CALCULATION DETAILS",
        printDetailSubtitle: "Calculation assumptions and cost breakdown",
        printConclusionTitle: "Conclusion",
        printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
        printBenefitSafeTitle: "Safer Workplace",
        printBenefitSafeDesc: "Reduce risk before work starts",
        printBenefitProdTitle: "Higher Productivity",
        printBenefitProdDesc: "Return inspection time to operations",
        printBenefitInvestTitle: "Smart Investment",
        printBenefitInvestDesc: "Clear annual saving and payback"
    },
    ja: {
        print: "印刷 / PDF保存",
        fullWidth: "全幅",
        fullWidthOn: "通常幅に戻す",
        fullWidthOff: "レイアウトを画面いっぱいに広げます",
        eyebrow: "Single Page ROI Tool",
        titleA: "従来方式のROIを",
        desc: "運用コスト、検査時間、Productivity Loss、Tenko Robot導入効果を顧客別プリセットで比較します。",
        inputTitle: "入力",
        inputSub: "数値を変更するとすぐに再計算されます。",
        operation: "1) Operation",
        staffCost: "2) Staff Cost",
        productivity: "3) Inspection Time Cost",
        equipment: "4) Conventional Equipment Cost",
        tenko: "5) Tenko Robot",
        workload: "WORKLOAD",
        cost: "COST",
        hiddenCost: "HIDDEN COST",
        equipmentTag: "EQUIPMENT",
        allIn: "ALL-IN",
        autoOtHint: "Default と Petchana は稼働率が 100% を超えると OT を自動計算し、Honda は 4 時間固定です。",
        autoOn: "Auto OT: ON - 稼働率 100% 超過分を自動計算",
        autoOff: "Auto OT: OFF - ユーザーまたは preset 指定",
        factorChoice: "Employee Cost Factor Choice",
        factorGeneral: "一般工場",
        factorGeneralDesc: "給与以外の基本コスト",
        factorJapanese: "日系工場",
        factorJapaneseDesc: "福利厚生と HR 基準が高い",
        factorMultinational: "多国籍企業",
        factorMultinationalDesc: "総人件費が給与より高い",
        factorCustom: "カスタム",
        factorHint: "Employee Cost Factor は給与以外の実コストです。社会保険、賞与、制服、福利厚生、休暇、教育、採用費を含みます。",
        reset: "Reset",
        saving: "年間コスト削減",
        timeSaving: "年間検査時間削減",
        prodSaving: "年間 Productivity Loss 削減",
        worth: "投資評価",
        worthGood: "効果あり",
        worthBad: "効果なし",
        worthGoodNote: "Tenko は年間コストを削減します",
        worthBadNote: "Tenko は従来方式より高コストです",
        oldMethod: "従来方式",
        annualCost: "Annual Operating Cost",
        annualTime: "Annual Inspection Time",
        prodLoss: "Employee Productivity Loss",
        totalCost: "Total Cost Incl. Productivity",
        execTitle: "Executive Summary",
        execDesc: "年間コストと時間削減の概要",
        costBreakTitle: "Cost Breakdown",
        costBreakDesc: "従来方式の人件費は固定 100% ではなく、実際の utilization で計算されます。",
        staffByUtil: "Utilization ベース人件費",
        baseSalary: "基本給 / 年",
        otCost: "OT コスト / 年",
        extras: "社会保険 + 賞与 + 休暇",
        dep: "設備償却 / 年",
        maint: "保守 / 年",
        cal: "校正 / 年",
        tenkoMonthly: "月額 x 12",
        setup: "初年度セットアップ",
        other: "その他 / 年",
        cycle: "従来サイクルタイム",
        costPerMin: "人件費 / 分",
        timeSaveDay: "削減検査時間 / 日",
        roiFromTotal: "総削減額ベース ROI",
        chartTitle: "Cumulative Cost Chart",
        chartDesc: "選択年数での Operating Cost + Productivity Loss",
        timeChartTitle: "Time Cost Chart",
        timeChartDesc: "Tenko の有無による年間検査時間と年間削減時間を比較します。",
        timeChartAnnual: "年間",
        timeChartSaved: "年間削減検査時間",
        start: "開始",
        year: "年",
        hours: "時間",
        min: "分",
        disclaimer: "このレポートは入力された前提条件に基づく試算です。実際の結果は運用条件により変動します。",
        assumptions: "Key Assumptions",
        formula: "Formula",
        utilTitle: "Inspection Staff Utilization",
        utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
        productivityPanelDesc: "Cycle time, utilization, employee cost, and returned working time.",
        printHeroTitle: "EXECUTIVE SUMMARY",
        printHeroSubtitle: "Annual ROI comparison: Conventional method vs Tenko Robot",
        printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
        printDetailTitle: "CALCULATION DETAILS",
        printDetailSubtitle: "Calculation assumptions and cost breakdown",
        printConclusionTitle: "Conclusion",
        printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
        printBenefitSafeTitle: "Safer Workplace",
        printBenefitSafeDesc: "Reduce risk before work starts",
        printBenefitProdTitle: "Higher Productivity",
        printBenefitProdDesc: "Return inspection time to operations",
        printBenefitInvestTitle: "Smart Investment",
        printBenefitInvestDesc: "Clear annual saving and payback"
    }
};
export const uiLabels = {
    th: {
        peoplePerDay: "จำนวนคนตรวจ / วัน",
        daysPerMonth: "วันตรวจ / เดือน",
        minutesPerPerson: "เวลาตรวจเดิม / คน",
        waitMinutes: "เวลารอ / เปลี่ยนคิว",
        tenkoMinutesPerPerson: "เวลา Tenko / คน",
        workDaysYear: "วันทำงาน / ปี",
        staffCount: "เจ้าหน้าที่ตรวจ",
        salaryPerMonth: "เงินเดือน / เดือน",
        otHoursPerDay: "OT ชม. / วัน / คน",
        otMultiplier: "ตัวคูณ OT",
        socialSecurityYear: "ประกันสังคม / ปี",
        bonusYear: "โบนัส / ปี",
        absenceYear: "วันลา / ปี",
        employeeAvgSalary: "เงินเดือนเฉลี่ยพนักงาน",
        workHoursDay: "ชั่วโมงทำงาน / วัน",
        employeeCostFactor: "Employee Cost Factor",
        alcBuy: "เครื่องเป่าแอลกอฮอล์",
        alcMaint: "บำรุงรักษาแอลกอฮอล์",
        alcCal: "สอบเทียบแอลกอฮอล์",
        alcLife: "อายุใช้งานแอลกอฮอล์",
        bpBuy: "เครื่องวัดความดัน",
        bpMaint: "บำรุงรักษาความดัน",
        bpCal: "สอบเทียบความดัน",
        bpLife: "อายุใช้งานความดัน",
        tempBuy: "เครื่องวัดอุณหภูมิ",
        tempMaint: "บำรุงรักษาอุณหภูมิ",
        tempCal: "สอบเทียบอุณหภูมิ",
        tempLife: "อายุใช้งานอุณหภูมิ",
        tenkoMonthly: "ค่า Tenko / เดือน",
        tenkoSetup: "Setup ปีแรก",
        tenkoOtherYear: "ค่าอื่น ๆ / ปี",
        years: "จำนวนปีที่ดูกราฟ"
    },
    en: {
        peoplePerDay: "Employees / day",
        daysPerMonth: "Inspection days / month",
        minutesPerPerson: "Conventional time / person",
        waitMinutes: "Waiting / changeover time",
        tenkoMinutesPerPerson: "Tenko time / person",
        workDaysYear: "Work days / year",
        staffCount: "Inspection staff",
        salaryPerMonth: "Salary / month",
        otHoursPerDay: "OT hours / day / person",
        otMultiplier: "OT multiplier",
        socialSecurityYear: "Social security / year",
        bonusYear: "Bonus / year",
        absenceYear: "Leave cost / year",
        employeeAvgSalary: "Average employee salary",
        workHoursDay: "Work hours / day",
        employeeCostFactor: "Employee Cost Factor",
        alcBuy: "Alcohol tester purchase",
        alcMaint: "Alcohol maintenance",
        alcCal: "Alcohol calibration",
        alcLife: "Alcohol life",
        bpBuy: "Blood pressure device",
        bpMaint: "BP maintenance",
        bpCal: "BP calibration",
        bpLife: "BP life",
        tempBuy: "Temperature device",
        tempMaint: "Temperature maintenance",
        tempCal: "Temperature calibration",
        tempLife: "Temperature life",
        tenkoMonthly: "Tenko fee / month",
        tenkoSetup: "First-year setup",
        tenkoOtherYear: "Other cost / year",
        years: "Chart years"
    },
    ja: {
        peoplePerDay: "検査人数 / 日",
        daysPerMonth: "検査日数 / 月",
        minutesPerPerson: "従来時間 / 人",
        waitMinutes: "待機 / 切替時間",
        tenkoMinutesPerPerson: "Tenko 時間 / 人",
        workDaysYear: "稼働日数 / 年",
        staffCount: "検査スタッフ",
        salaryPerMonth: "給与 / 月",
        otHoursPerDay: "OT 時間 / 日 / 人",
        otMultiplier: "OT 係数",
        socialSecurityYear: "社会保険 / 年",
        bonusYear: "賞与 / 年",
        absenceYear: "休暇コスト / 年",
        employeeAvgSalary: "平均給与",
        workHoursDay: "勤務時間 / 日",
        employeeCostFactor: "Employee Cost Factor",
        alcBuy: "アルコール測定器購入",
        alcMaint: "アルコール保守",
        alcCal: "アルコール校正",
        alcLife: "アルコール耐用年数",
        bpBuy: "血圧計購入",
        bpMaint: "血圧計保守",
        bpCal: "血圧計校正",
        bpLife: "血圧計耐用年数",
        tempBuy: "体温計購入",
        tempMaint: "体温計保守",
        tempCal: "体温計校正",
        tempLife: "体温計耐用年数",
        tenkoMonthly: "Tenko 月額",
        tenkoSetup: "初年度セットアップ",
        tenkoOtherYear: "その他費用 / 年",
        years: "グラフ年数"
    }
};
export const uiFactorChoices = [
    { value: "1.20", title: "factorGeneral", desc: "factorGeneralDesc" },
    { value: "1.25", title: "factorJapanese", desc: "factorJapaneseDesc" },
    { value: "1.35", title: "factorMultinational", desc: "factorMultinationalDesc" },
    { value: "custom", title: "factorCustom", desc: "factorHint" }
];
export const uiGroups = [
    {
        title: "operation",
        tag: "workload",
        keys: [
            "peoplePerDay",
            "daysPerMonth",
            "minutesPerPerson",
            "waitMinutes",
            "tenkoMinutesPerPerson",
            "workDaysYear",
            "staffCount",
            "otHoursPerDay"
        ]
    },
    {
        title: "staffCost",
        tag: "cost",
        keys: ["salaryPerMonth", "otMultiplier", "socialSecurityYear", "bonusYear", "absenceYear"]
    },
    {
        title: "productivity",
        tag: "hiddenCost",
        keys: ["employeeAvgSalary", "workHoursDay"]
    },
    {
        title: "equipment",
        tag: "equipmentTag",
        keys: [
            "alcBuy",
            "alcMaint",
            "alcCal",
            "alcLife",
            "bpBuy",
            "bpMaint",
            "bpCal",
            "bpLife",
            "tempBuy",
            "tempMaint",
            "tempCal",
            "tempLife"
        ]
    },
    {
        title: "tenko",
        tag: "allIn",
        keys: ["tenkoMonthly", "tenkoSetup", "tenkoOtherYear", "years"]
    }
];
