export const uiText = {
  th: {
    print: "พิมพ์ / Save PDF",
    fullWidth: "เต็มจอ",
    fullWidthOn: "กลับสู่ขนาดปกติ",
    fullWidthOff: "ขยาย layout ให้เต็มพื้นที่",
    eyebrow: "Single Page ROI Tool",
    titleA: "คำนวณ ROI แบบเดิม เทียบกับ",
    desc: "คำนวณต้นทุน เวลา Productivity Loss และความคุ้มค่าของ Tenko Robot พร้อม preset สำหรับแต่ละลูกค้า",
    inputTitle: "กรอกข้อมูล",
    inputSub: "แก้ตัวเลขได้ทันที ระบบจะคำนวณใหม่อัตโนมัติ",
    operation: "1) Operation",
    staffCost: "2) Staff Cost",
    productivity: "3) Inspection Time Cost",
    equipment: "4) Equipment Cost แบบเดิม",
    tenko: "5) Tenko Robot",
    workload: "WORKLOAD",
    cost: "COST",
    hiddenCost: "HIDDEN COST",
    equipmentTag: "EQUIPMENT",
    allIn: "ALL-IN",
    autoOtHint: "Default และเพชรชนะ: ถ้า Utilization เกิน 100% ระบบจะเติม OT อัตโนมัติจากเวลาที่เกิน 480 นาที/วัน/คน และผู้ใช้ยังแก้ค่า OT ต่อเองได้ · Honda: ใช้ OT 4 ชม. เป็นค่า override",
    autoOn: "Auto OT: เปิดอยู่ — คำนวณจาก Utilization ที่เกิน 100%",
    autoOff: "Auto OT: ปิดแล้ว — ผู้ใช้ปรับค่าเอง",
    factorChoice: "Employee Cost Factor",
    factorGeneral: "โรงงานทั่วไป",
    factorGeneralDesc: "ต้นทุนพื้นฐานนอกเหนือเงินเดือน",
    factorJapanese: "โรงงานญี่ปุ่น",
    factorJapaneseDesc: "สวัสดิการและมาตรฐาน HR สูงขึ้น",
    factorMultinational: "บริษัทข้ามชาติ",
    factorMultinationalDesc: "ต้นทุนพนักงานรวมสูงกว่าเงินเดือนมาก",
    factorCustom: "กำหนดเอง",
    factorHint: "Employee Cost Factor คือต้นทุนจริงของพนักงานนอกเหนือจากเงินเดือน เช่น ประกันสังคม โบนัส ยูนิฟอร์ม สวัสดิการ วันลา อบรม และค่า recruit/onboarding",
    reset: "Reset",
    saving: "ประหยัดเงิน / ปี",
    timeSaving: "ประหยัดเวลาตรวจ / ปี",
    prodSaving: "ประหยัด Productivity Loss / ปี",
    worth: "ความคุ้มค่า",
    worthGood: "คุ้มค่า",
    worthBad: "ไม่คุ้มค่า",
    worthGoodNote: "Tenko ประหยัดกว่าต่อปี",
    worthBadNote: "Tenko มีต้นทุนสูงกว่าแบบเดิม",
    oldMethod: "แบบเดิม",
    diffColumn: "Difference",
    annualCost: "Annual Operating Cost",
    annualTime: "Annual Inspection Time",
    prodLoss: "Employee Productivity Loss",
    totalCost: "Total Cost Incl. Productivity",
    execTitle: "Executive Summary",
    execDesc: "สรุปต้นทุนและเวลาที่ประหยัดได้ต่อปี",
    costBreakTitle: "Cost Breakdown",
    costBreakDesc: "ต้นทุนแบบเดิมคิดค่าเจ้าหน้าที่ตาม utilization จริง ไม่ใช่เต็ม 100%",
    staffByUtil: "ค่าเจ้าหน้าที่ตาม Utilization",
    recordingStaff: "ค่าเจ้าหน้าที่จดบันทึก",
    automated: "อัตโนมัติ",
    baseSalary: "เงินเดือนฐาน / ปี",
    otCost: "ค่า OT / ปี",
    extras: "ประกันสังคม + โบนัส + วันลา",
    dep: "ค่าเสื่อมอุปกรณ์ / ปี",
    maint: "บำรุงรักษา / ปี",
    cal: "สอบเทียบ / ปี",
    tenkoMonthly: "รายเดือน x 12",
    setup: "Setup ปีแรก",
    other: "อื่น ๆ / ปี",
    cycle: "Cycle Time แบบเดิม",
    costPerMin: "ต้นทุนพนักงาน / นาที",
    timeSaveDay: "เวลาตรวจที่ประหยัด / วัน",
    roiFromTotal: "ROI จาก Total Saving",
    chartTitle: "Cumulative Cost Chart",
    chartDesc: "Operating Cost + Productivity Loss ตามจำนวนปีที่เลือก",
    timeChartTitle: "Cumulative Inspection Time",
    timeChartDesc: "เทียบเวลาตรวจต่อปีแบบมีและไม่มี Tenko พร้อมเวลาที่ประหยัดได้",
    timeChartAnnual: "ต่อปี",
    timeChartSaved: "ประหยัดเวลาตรวจ / ปี",
    start: "เริ่มต้น",
    year: "ปี",
    hours: "ชม.",
    min: "นาที",
    disclaimer: "รายงานนี้เป็นการประเมินจากข้อมูลและสมมติฐานที่ผู้ใช้กรอก ผลลัพธ์จริงอาจเปลี่ยนตามสภาพการใช้งานจริง",
    assumptions: "สมมติฐานหลัก",
    formula: "Formula",
    utilTitle: "Inspection Staff Utilization",
    utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
    productivityPanelTitle: "Productivity & Staffing Analysis",
    productivityPanelDesc: "เห็นทั้ง Cycle Time, Utilization, ต้นทุนต่อนาที และเวลาที่คืนกลับให้องค์กร",
    printHeroTitle: "Executive Summary",
    printHeroSubtitle: "Annual ROI comparison: Conventional method vs Tenko Robot",
    printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
    printDetailTitle: "รายละเอียดการคำนวณ",
    printDetailSubtitle: "Calculation assumptions and cost breakdown",
    staffCostTitle: "ต้นทุนเจ้าหน้าที่",
    equipCostTitle: "ต้นทุนอุปกรณ์แบบเดิม",
    tenkoCostTitle: "ต้นทุน Tenko Robot",
    printNote: "Productivity Loss = จำนวนพนักงาน × วันตรวจ × เวลาตรวจ × ต้นทุนต่อนาทีของผู้เข้าตรวจ",
    printConclusionTitle: "Conclusion",
    printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
    printBenefitSafeTitle: "Safer Workplace",
    printBenefitSafeDesc: "Reduce risk before work starts",
    printBenefitProdTitle: "Higher Productivity",
    printBenefitProdDesc: "Return inspection time to operations",
    printBenefitInvestTitle: "Smart Investment",
    printBenefitInvestDesc: "Clear annual saving and payback",
  },
  en: {
    print: "Print / Save PDF",
    fullWidth: "Full width",
    fullWidthOn: "Return to normal width",
    fullWidthOff: "Expand the layout to fill the screen",
    eyebrow: "Single Page ROI Tool",
    titleA: "Calculate conventional ROI versus",
    desc: "Estimate operating cost, inspection time, productivity loss, and Tenko Robot investment impact with customer presets.",
    inputTitle: "Inputs",
    inputSub: "Edit values and the calculator updates immediately.",
    operation: "1) Operation",
    staffCost: "2) Staff Cost",
    productivity: "3) Inspection Time Cost",
    equipment: "4) Conventional Equipment Cost",
    tenko: "5) Tenko Robot",
    workload: "WORKLOAD",
    cost: "COST",
    hiddenCost: "HIDDEN COST",
    equipmentTag: "EQUIPMENT",
    allIn: "ALL-IN",
    autoOtHint: "Default and Petchana: if utilization exceeds 100%, OT is automatically filled from time beyond 480 minutes/day/person, and the user can still edit OT. Honda uses 4 hours OT as an override.",
    autoOn: "Auto OT: On — calculated from utilization above 100%",
    autoOff: "Auto OT: Off — user-edited OT value",
    factorChoice: "Employee Cost Factor",
    factorGeneral: "General factory",
    factorGeneralDesc: "Basic cost beyond salary",
    factorJapanese: "Japanese factory",
    factorJapaneseDesc: "Higher welfare and HR standards",
    factorMultinational: "Multinational",
    factorMultinationalDesc: "Total employee cost is much higher than salary",
    factorCustom: "Custom",
    factorHint: "Employee Cost Factor represents real employee cost beyond salary, including social security, bonus, uniform, welfare, leave, training, and recruiting/onboarding.",
    reset: "Reset",
    saving: "Annual cost saving",
    timeSaving: "Annual inspection time saving",
    prodSaving: "Annual productivity loss saving",
    worth: "Investment result",
    worthGood: "Worth it",
    worthBad: "Not worth it",
    worthGoodNote: "Tenko saves annual cost",
    worthBadNote: "Tenko costs more than the conventional method",
    oldMethod: "Conventional",
    diffColumn: "Difference",
    annualCost: "Annual Operating Cost",
    annualTime: "Annual Inspection Time",
    prodLoss: "Employee Productivity Loss",
    totalCost: "Total Cost Incl. Productivity",
    execTitle: "Executive Summary",
    execDesc: "Annual cost and time saving summary",
    costBreakTitle: "Cost Breakdown",
    costBreakDesc: "Conventional staff cost is calculated by real inspection utilization, not fixed at 100%.",
    staffByUtil: "Staff cost by utilization",
    recordingStaff: "Recording Staff Cost",
    automated: "Automated",
    baseSalary: "Base salary / year",
    otCost: "OT cost / year",
    extras: "Social security + bonus + leave",
    dep: "Equipment depreciation / year",
    maint: "Maintenance / year",
    cal: "Calibration / year",
    tenkoMonthly: "Monthly fee x 12",
    setup: "First-year setup",
    other: "Other cost / year",
    cycle: "Conventional cycle time",
    costPerMin: "Employee cost / minute",
    timeSaveDay: "Inspection time saved / day",
    roiFromTotal: "ROI from total saving",
    chartTitle: "Cumulative Cost Chart",
    chartDesc: "Operating cost + productivity loss by selected year range",
    timeChartTitle: "Cumulative Inspection Time",
    timeChartDesc: "Compare annual inspection time with and without Tenko, plus annual time saved.",
    timeChartAnnual: "Annual",
    timeChartSaved: "Inspection time saved / year",
    start: "Start",
    year: "Year",
    hours: "hr",
    min: "min",
    disclaimer: "This report is an estimate based on user-entered assumptions. Actual results may vary by real operating conditions.",
    assumptions: "Key Assumptions",
    formula: "Formula",
    utilTitle: "Inspection Staff Utilization",
    utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
    productivityPanelTitle: "Productivity & Staffing Analysis",
    productivityPanelDesc: "Cycle time, utilization, employee cost, and returned working time.",
    printHeroTitle: "Executive Summary",
    printHeroSubtitle: "Annual ROI comparison: Conventional method vs Tenko Robot",
    printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
    printDetailTitle: "Calculation Details",
    printDetailSubtitle: "Calculation assumptions and cost breakdown",
    staffCostTitle: "Staff Cost",
    equipCostTitle: "Conventional Equipment Cost",
    tenkoCostTitle: "Tenko Robot Cost",
    printNote: "Productivity Loss = employees × inspection days × inspection time × cost per minute of inspected employees.",
    printConclusionTitle: "Conclusion",
    printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
    printBenefitSafeTitle: "Safer Workplace",
    printBenefitSafeDesc: "Reduce risk before work starts",
    printBenefitProdTitle: "Higher Productivity",
    printBenefitProdDesc: "Return inspection time to operations",
    printBenefitInvestTitle: "Smart Investment",
    printBenefitInvestDesc: "Clear annual saving and payback",
  },
  ja: {
    print: "印刷 / PDF保存",
    fullWidth: "全幅",
    fullWidthOn: "通常幅に戻す",
    fullWidthOff: "レイアウトを画面いっぱいに広げます",
    eyebrow: "Single Page ROI Tool",
    titleA: "従来方式のROIを",
    desc: "運用コスト、検査時間、Productivity Loss、Tenko Robot導入効果を顧客別プリセットで比較します。",
    inputTitle: "入力",
    inputSub: "数値を変更するとすぐに再計算されます。",
    operation: "1) オペレーション",
    staffCost: "2) 担当者コスト",
    productivity: "3) 検査時間コスト",
    equipment: "4) 従来設備コスト",
    tenko: "5) Tenko Robot",
    workload: "WORKLOAD",
    cost: "COST",
    hiddenCost: "HIDDEN COST",
    equipmentTag: "EQUIPMENT",
    allIn: "ALL-IN",
    autoOtHint: "デフォルトとペッチャナでは、稼働率が100%を超えると480分/日/人を超過した分からOTを自動入力します。ユーザーは後で編集できます。HondaはOT 4時間を上書き値として使用します。",
    autoOn: "Auto OT: ON — 稼働率100%超過分から計算",
    autoOff: "Auto OT: OFF — ユーザー編集済み",
    factorChoice: "Employee Cost Factor",
    factorGeneral: "一般工場",
    factorGeneralDesc: "給与以外の基本コスト",
    factorJapanese: "日系工場",
    factorJapaneseDesc: "福利厚生と HR 基準が高い",
    factorMultinational: "多国籍企業",
    factorMultinationalDesc: "総人件費が給与より高い",
    factorCustom: "カスタム",
    factorHint: "Employee Cost Factor は給与以外の実コストです。社会保険、賞与、制服、福利厚生、休暇、教育、採用費を含みます。",
    reset: "Reset",
    saving: "年間コスト削減",
    timeSaving: "年間検査時間削減",
    prodSaving: "年間 Productivity Loss 削減",
    worth: "投資評価",
    worthGood: "効果あり",
    worthBad: "効果なし",
    worthGoodNote: "Tenko は年間コストを削減します",
    worthBadNote: "Tenko は従来方式より高コストです",
    oldMethod: "従来方式",
    diffColumn: "Difference",
    annualCost: "Annual Operating Cost",
    annualTime: "Annual Inspection Time",
    prodLoss: "Employee Productivity Loss",
    totalCost: "Total Cost Incl. Productivity",
    execTitle: "Executive Summary",
    execDesc: "年間コストと時間削減の概要",
    costBreakTitle: "Cost Breakdown",
    costBreakDesc: "従来方式の人件費は固定 100% ではなく、実際の utilization で計算されます。",
    staffByUtil: "Utilization ベース人件費",
    recordingStaff: "記録担当者コスト",
    automated: "自動化",
    baseSalary: "基本給 / 年",
    otCost: "OT コスト / 年",
    extras: "社会保険 + 賞与 + 休暇",
    dep: "設備償却 / 年",
    maint: "保守 / 年",
    cal: "校正 / 年",
    tenkoMonthly: "月額 x 12",
    setup: "初年度セットアップ",
    other: "その他 / 年",
    cycle: "従来サイクルタイム",
    costPerMin: "人件費 / 分",
    timeSaveDay: "削減検査時間 / 日",
    roiFromTotal: "総削減額ベース ROI",
    chartTitle: "Cumulative Cost Chart",
    chartDesc: "選択年数での Operating Cost + Productivity Loss",
    timeChartTitle: "Cumulative Inspection Time",
    timeChartDesc: "Tenko の有無による年間検査時間と年間削減時間を比較します。",
    timeChartAnnual: "年間",
    timeChartSaved: "年間削減検査時間",
    start: "開始",
    year: "年",
    hours: "時間",
    min: "分",
    disclaimer: "このレポートは入力された前提条件に基づく試算です。実際の結果は運用条件により変動します。",
    assumptions: "主要前提",
    formula: "Formula",
    utilTitle: "Inspection Staff Utilization",
    utilLegend: "Excellent 0-60% | Normal 60-80% | Busy 80-100% | Overloaded >100%",
    productivityPanelTitle: "生産性・人員分析",
    productivityPanelDesc: "サイクルタイム、稼働率、1分あたりコスト、組織に戻る時間を確認します。",
    printHeroTitle: "エグゼクティブサマリー",
    printHeroSubtitle: "年間ROI比較：従来方式 vs Tenko Robot",
    printBrandSmall: "AI ROBOT FOR SAFER WORKPLACE",
    printDetailTitle: "計算詳細",
    printDetailSubtitle: "計算前提とコスト内訳",
    staffCostTitle: "担当者コスト",
    equipCostTitle: "従来設備コスト",
    tenkoCostTitle: "Tenko Robot コスト",
    printNote: "生産性損失 = 従業員数 × 検査日数 × 検査時間 × 検査対象者の1分あたりコスト",
    printConclusionTitle: "Conclusion",
    printConclusionLine: "Tenko Robot reduces annual cost and inspection time when compared with the current process.",
    printBenefitSafeTitle: "Safer Workplace",
    printBenefitSafeDesc: "Reduce risk before work starts",
    printBenefitProdTitle: "Higher Productivity",
    printBenefitProdDesc: "Return inspection time to operations",
    printBenefitInvestTitle: "Smart Investment",
    printBenefitInvestDesc: "Clear annual saving and payback",
  },
}
export const uiLabels = {
  th: {
    peoplePerDay: "จำนวนพนักงานที่ตรวจ / วัน",
    daysPerMonth: "จำนวนวันตรวจ / เดือน",
    minutesPerPerson: "เวลาแบบเดิมต่อคน รวมจดบันทึก (นาที)",
    waitMinutes: "เวลารอ/เปลี่ยนคนถัดไป (นาที)",
    tenkoMinutesPerPerson: "เวลา Tenko ต่อคน รวมบันทึกอัตโนมัติ (นาที)",
    workDaysYear: "วันทำงานเทียบต้นทุนพนักงาน / ปี",
    staffCount: "จำนวน จนท.คุมการตรวจ (คน)",
    salaryPerMonth: "เงินเดือน จนท. / เดือน (บาท)",
    otHoursPerDay: "จำนวนชม.เฉลี่ยทำ OT / วัน / คน",
    otMultiplier: "ตัวคูณ OT",
    socialSecurityYear: "ประกันสังคม / ปี / คน",
    bonusYear: "โบนัส / ปี / คน",
    absenceYear: "ต้นทุนวันลา/ขาดงาน / ปี / คน",
    employeeAvgSalary: "เงินเดือนเฉลี่ยผู้เข้าตรวจ / เดือน",
    workHoursDay: "ชั่วโมงทำงาน / วัน",
    employeeCostFactor: "Custom Employee Cost Factor",
    alcBuy: "Alcohol ราคาซื้อ",
    alcMaint: "Alcohol ซ่อมบำรุง/ปี",
    alcCal: "Alcohol calibration/ปี",
    alcLife: "Alcohol อายุใช้งาน (ปี)",
    bpBuy: "BP ราคาซื้อ",
    bpMaint: "BP ซ่อมบำรุง/ปี",
    bpCal: "BP calibration/ปี",
    bpLife: "BP อายุใช้งาน (ปี)",
    tempBuy: "Temp ราคาซื้อ",
    tempMaint: "Temp ซ่อมบำรุง/ปี",
    tempCal: "Temp calibration/ปี",
    tempLife: "Temp อายุใช้งาน (ปี)",
    tenkoMonthly: "ค่าบริการ Tenko / เดือน",
    tenkoSetup: "ค่าติดตั้ง / setup",
    tenkoOtherYear: "ค่าอื่นๆ Tenko / ปี",
    years: "จำนวนปีที่ต้องการดู",
  },
  en: {
    peoplePerDay: "Employees inspected / day",
    daysPerMonth: "Inspection days / month",
    minutesPerPerson: "Conventional time per person incl. recording (min)",
    waitMinutes: "Waiting / changeover time (min)",
    tenkoMinutesPerPerson: "Tenko time per person incl. auto recording (min)",
    workDaysYear: "Working days for labor cost / year",
    staffCount: "Inspection staff (people)",
    salaryPerMonth: "Staff salary / month (THB)",
    otHoursPerDay: "Average OT hours / day / person",
    otMultiplier: "OT multiplier",
    socialSecurityYear: "Social security / year / person",
    bonusYear: "Bonus / year / person",
    absenceYear: "Leave / absence cost / year / person",
    employeeAvgSalary: "Average salary of inspected employee / month",
    workHoursDay: "Working hours / day",
    employeeCostFactor: "Custom Employee Cost Factor",
    alcBuy: "Alcohol tester purchase price",
    alcMaint: "Alcohol tester maintenance / year",
    alcCal: "Alcohol tester calibration / year",
    alcLife: "Alcohol tester useful life (years)",
    bpBuy: "BP monitor purchase price",
    bpMaint: "BP monitor maintenance / year",
    bpCal: "BP monitor calibration / year",
    bpLife: "BP monitor useful life (years)",
    tempBuy: "Thermometer purchase price",
    tempMaint: "Thermometer maintenance / year",
    tempCal: "Thermometer calibration / year",
    tempLife: "Thermometer useful life (years)",
    tenkoMonthly: "Tenko monthly fee",
    tenkoSetup: "Setup / installation",
    tenkoOtherYear: "Other Tenko cost / year",
    years: "Years to display",
  },
  ja: {
    peoplePerDay: "1日あたり検査人数",
    daysPerMonth: "月あたり検査日数",
    minutesPerPerson: "従来方式 1人あたり時間（記録含む・分）",
    waitMinutes: "待機 / 入替時間（分）",
    tenkoMinutesPerPerson: "Tenko 1人あたり時間（自動記録含む・分）",
    workDaysYear: "人件費計算用 営業日数 / 年",
    staffCount: "検査担当者数",
    salaryPerMonth: "担当者給与 / 月（THB）",
    otHoursPerDay: "平均残業時間 / 日 / 人",
    otMultiplier: "残業倍率",
    socialSecurityYear: "社会保険 / 年 / 人",
    bonusYear: "賞与 / 年 / 人",
    absenceYear: "休暇・欠勤コスト / 年 / 人",
    employeeAvgSalary: "検査対象者の平均給与 / 月",
    workHoursDay: "勤務時間 / 日",
    employeeCostFactor: "カスタム Employee Cost Factor",
    alcBuy: "アルコール検知器 購入価格",
    alcMaint: "アルコール検知器 保守 / 年",
    alcCal: "アルコール検知器 校正 / 年",
    alcLife: "アルコール検知器 耐用年数",
    bpBuy: "血圧計 購入価格",
    bpMaint: "血圧計 保守 / 年",
    bpCal: "血圧計 校正 / 年",
    bpLife: "血圧計 耐用年数",
    tempBuy: "体温計 購入価格",
    tempMaint: "体温計 保守 / 年",
    tempCal: "体温計 校正 / 年",
    tempLife: "体温計 耐用年数",
    tenkoMonthly: "Tenko 月額費用",
    tenkoSetup: "セットアップ / 設置",
    tenkoOtherYear: "その他Tenko費用 / 年",
    years: "表示年数",
  },
}
export const uiFactorChoices = [
  { value: "1.20", title: "factorGeneral", desc: "factorGeneralDesc" },
  { value: "1.25", title: "factorJapanese", desc: "factorJapaneseDesc" },
  { value: "1.35", title: "factorMultinational", desc: "factorMultinationalDesc" },
  { value: "custom", title: "factorCustom", desc: "factorHint" },
]
export const uiGroups = [
  {
    title: "operation",
    tag: "workload",
    keys: [
      "peoplePerDay",
      "daysPerMonth",
      "minutesPerPerson",
      "waitMinutes",
      "tenkoMinutesPerPerson",
      "workDaysYear",
      "staffCount",
      "otHoursPerDay",
    ],
  },
  {
    title: "staffCost",
    tag: "cost",
    keys: ["salaryPerMonth", "otMultiplier", "socialSecurityYear", "bonusYear", "absenceYear"],
  },
  {
    title: "productivity",
    tag: "hiddenCost",
    keys: ["employeeAvgSalary", "workHoursDay"],
  },
  {
    title: "equipment",
    tag: "equipmentTag",
    keys: [
      "alcBuy",
      "alcMaint",
      "alcCal",
      "alcLife",
      "bpBuy",
      "bpMaint",
      "bpCal",
      "bpLife",
      "tempBuy",
      "tempMaint",
      "tempCal",
      "tempLife",
    ],
  },
  {
    title: "tenko",
    tag: "allIn",
    keys: ["tenkoMonthly", "tenkoSetup", "tenkoOtherYear", "years"],
  },
]
